dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else

linter:
  rules:
    # ERRORS
    - cancel_subscriptions
    - empty_statements
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - use_key_in_widget_constructors

    # STYLE
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - always_specify_types
    - avoid_bool_literals_in_conditional_expressions
    - avoid_double_and_int_checks
    - avoid_positional_boolean_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_unnecessary_containers
    - avoid_void_async
    - camel_case_types
    - camel_case_extensions
    - file_names
    - flutter_style_todos
    - leading_newlines_in_multiline_strings
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - use_full_hex_values_for_flutter_colors
    - use_is_even_rather_than_modulo
    - void_checks

    # DOCUMENTATION

    # USAGE
    - implementation_imports
    - always_use_package_imports
    - unnecessary_new
    - unnecessary_const

    # DESIGN