name: yc_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  connectivity: ^3.0.6
  flutter_html: ^2.2.1
  flutter_markdown: ^0.6.2
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.7
  graphql_flutter: ^5.0.0
  http: ^0.13.3
  infinite_listview: ^1.1.0
  intl: ^0.17.0
  lottie: ^1.1.0
  native_device_orientation: ^1.0.0
  page_transition: ^2.0.2
  rect_getter: ^1.0.0
  rxdart: ^0.26.0
  scroll_to_index: ^2.1.0
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  smooth_page_indicator: ^0.3.0-nullsafety.0
  tuple: ^2.0.0
  video_player: ^2.2.7
  visibility_detector: ^0.2.0
  wakelock: ^0.5.3+3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  dart_code_metrics: ^4.8.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/videos/
    - assets/gifs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
    - family: Nunito-Bold
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
    - family: Nunito-Semi
      fonts:
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
    - family: Nunito-ExtraBold
      fonts:
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
